/**
 * "Copy page" control for docs and blog posts: a split button whose main
 * action copies the page as Markdown, with a menu for viewing that Markdown
 * or opening it in an AI tool.
 *
 * Every action works from one `PageSnapshot` generated by `capture()` (the
 * page's rendered content run through `domToMarkdown`), so copy, view, and
 * each AI tool always see identical text. The menu follows the same
 * button + dropdown pattern as src/theme/ColorModeToggle.
 */
import React, {
  type KeyboardEvent,
  type ReactNode,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';
import clsx from 'clsx';
import useIsBrowser from '@docusaurus/useIsBrowser';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import {translate} from '@docusaurus/Translate';
import {
  AI_TOOLS,
  buildAiLaunch,
  type AiTool,
  type PageSnapshot,
} from './aiTools';
import {copyToClipboard, type CopyStatus} from './clipboard';
import {domToMarkdown} from './domToMarkdown';
import {
  AlertIcon,
  CheckIcon,
  CopyIcon,
  ExternalLinkIcon,
  FileTextIcon,
} from './icons';
import MarkdownDialog from './MarkdownDialog';
import styles from './styles.module.css';

const FEEDBACK_MS = 2500;

const TEXT = {
  copyPage: translate({
    message: 'Copy page',
    id: 'copyPage.button.copy',
    description: 'Main button: copy the current page as Markdown',
  }),
  copied: translate({
    message: 'Copied',
    id: 'copyPage.button.copied',
    description: 'Main button label after the page was copied',
  }),
  failed: translate({
    message: 'Copy failed',
    id: 'copyPage.button.failed',
    description: 'Main button label when copying to the clipboard failed',
  }),
  moreActions: translate({
    message: 'More page actions',
    id: 'copyPage.toggle.ariaLabel',
    description: 'aria-label of the dropdown arrow next to the Copy page button',
  }),
  menuCopy: translate({
    message: 'Copy as Markdown',
    id: 'copyPage.menu.copy',
    description: 'Menu item: copy the page as Markdown',
  }),
  menuView: translate({
    message: 'View as Markdown',
    id: 'copyPage.menu.view',
    description: 'Menu item: show the page as raw Markdown in a dialog',
  }),
  announceCopied: translate({
    message: 'Page copied as Markdown to the clipboard.',
    id: 'copyPage.announce.copied',
    description: 'Screen reader announcement after a successful copy',
  }),
  announceFailed: translate({
    message:
      'Could not copy to the clipboard. Use View as Markdown to copy it manually.',
    id: 'copyPage.announce.failed',
    description: 'Screen reader announcement after a failed copy',
  }),
};

function openInLabel(tool: AiTool): string {
  return translate(
    {
      message: 'Open in {tool}',
      id: 'copyPage.menu.openIn',
      description: 'Menu item: open the page in an AI tool, e.g. "Open in Claude"',
    },
    {tool: tool.label},
  );
}

function announcePasteHint(tool: AiTool): string {
  return translate(
    {
      message:
        'Page copied as Markdown. Paste it into {tool} if it cannot open the link.',
      id: 'copyPage.announce.pasteHint',
      description:
        'Announcement when a page was too long to send to an AI tool in the link and was copied instead',
    },
    {tool: tool.label},
  );
}

export default function CopyPage(): ReactNode {
  const isBrowser = useIsBrowser();
  const {siteConfig} = useDocusaurusContext();
  const rootRef = useRef<HTMLDivElement>(null);
  const toggleRef = useRef<HTMLButtonElement>(null);
  const menuRef = useRef<HTMLUListElement>(null);
  const feedbackTimer = useRef<number | undefined>(undefined);

  const [menuPage, setMenuPage] = useState<PageSnapshot | null>(null);
  const [viewing, setViewing] = useState<PageSnapshot | null>(null);
  const [status, setStatus] = useState<CopyStatus>('idle');
  const [announcement, setAnnouncement] = useState('');
  const open = menuPage !== null;

  useEffect(() => () => window.clearTimeout(feedbackTimer.current), []);

  const report = useCallback((next: CopyStatus, message: string) => {
    setStatus(next);
    setAnnouncement(message);
    window.clearTimeout(feedbackTimer.current);
    feedbackTimer.current = window.setTimeout(() => {
      setStatus('idle');
      setAnnouncement('');
    }, FEEDBACK_MS);
  }, []);

  /** Generates the Markdown for the page this control sits in. */
  const capture = useCallback((): PageSnapshot | null => {
    const article = rootRef.current?.closest('article');
    const content = article?.querySelector('.markdown');
    if (!article || !content) return null;
    const title =
      article.querySelector('h1')?.textContent?.trim() || document.title;
    return {
      // Blog posts keep their title in a header outside the .markdown
      // content, so it's passed separately (docs already include theirs).
      markdown: domToMarkdown(content, {baseUrl: window.location.href, title}),
      url: window.location.origin + window.location.pathname,
      title,
      siteName: siteConfig.title,
      description:
        document
          .querySelector<HTMLMetaElement>('meta[name="description"]')
          ?.content.trim() ?? '',
    };
  }, [siteConfig.title]);

  const copy = useCallback(
    async (page: PageSnapshot | null, pasteHintFor?: AiTool) => {
      const copied = page ? await copyToClipboard(page.markdown) : false;
      if (!copied) return report('error', TEXT.announceFailed);
      report(
        'copied',
        pasteHintFor ? announcePasteHint(pasteHintFor) : TEXT.announceCopied,
      );
    },
    [report],
  );

  const closeMenu = useCallback((restoreFocus: boolean) => {
    setMenuPage(null);
    if (restoreFocus) toggleRef.current?.focus();
  }, []);

  const openMenu = useCallback(() => {
    const page = capture();
    if (page) setMenuPage(page);
    else report('error', TEXT.announceFailed);
  }, [capture, report]);

  // Move focus into the menu when it opens.
  useEffect(() => {
    if (open) menuRef.current?.querySelector<HTMLElement>('[role="menuitem"]')?.focus();
  }, [open]);

  // Close on outside click.
  useEffect(() => {
    if (!open) return undefined;
    function handlePointerDown(event: PointerEvent) {
      if (!rootRef.current?.contains(event.target as Node)) setMenuPage(null);
    }
    document.addEventListener('pointerdown', handlePointerDown);
    return () => document.removeEventListener('pointerdown', handlePointerDown);
  }, [open]);

  const launches = useMemo(
    () =>
      menuPage
        ? AI_TOOLS.map((tool) => ({tool, ...buildAiLaunch(tool, menuPage)}))
        : [],
    [menuPage],
  );

  function handleKeyDown(event: KeyboardEvent) {
    if (!open) {
      if (event.key === 'ArrowDown' && event.target === toggleRef.current) {
        event.preventDefault();
        openMenu();
      }
      return;
    }
    if (event.key === 'Escape') {
      event.preventDefault();
      closeMenu(true);
      return;
    }
    if (event.key === 'Tab') {
      // Hand focus back to the toggle so Tab continues from there rather
      // than from the menu item that is about to be removed.
      closeMenu(true);
      return;
    }
    const items = Array.from(
      menuRef.current?.querySelectorAll<HTMLElement>('[role="menuitem"]') ?? [],
    );
    const current = items.indexOf(document.activeElement as HTMLElement);
    let next = -1;
    if (event.key === 'ArrowDown') next = (current + 1) % items.length;
    else if (event.key === 'ArrowUp') next = (current - 1 + items.length) % items.length;
    else if (event.key === 'Home') next = 0;
    else if (event.key === 'End') next = items.length - 1;
    if (next >= 0) {
      event.preventDefault();
      items[next]?.focus();
    }
  }

  const label =
    status === 'copied' ? TEXT.copied : status === 'error' ? TEXT.failed : TEXT.copyPage;
  const StatusIcon =
    status === 'copied' ? CheckIcon : status === 'error' ? AlertIcon : CopyIcon;

  return (
    <div className={styles.root} ref={rootRef} onKeyDown={handleKeyDown}>
      <div className={styles.group}>
        <button
          type="button"
          className={clsx(
            styles.mainButton,
            status === 'copied' && styles.statusCopied,
            status === 'error' && styles.statusError,
          )}
          disabled={!isBrowser}
          onClick={() => {
            closeMenu(false);
            void copy(capture());
          }}>
          <StatusIcon />
          <span>{label}</span>
        </button>
        <button
          type="button"
          ref={toggleRef}
          className={styles.toggleButton}
          disabled={!isBrowser}
          aria-haspopup="menu"
          aria-expanded={open}
          aria-label={TEXT.moreActions}
          title={TEXT.moreActions}
          onClick={() => (open ? closeMenu(false) : openMenu())}>
          <svg width="10" height="6" viewBox="0 0 10 6" aria-hidden="true">
            <path
              d="M1 1l4 4 4-4"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </div>

      {open && menuPage && (
        <ul className={styles.menu} role="menu" ref={menuRef}>
          <li role="none">
            <button
              type="button"
              role="menuitem"
              className={styles.menuItem}
              onClick={() => {
                closeMenu(true);
                void copy(menuPage);
              }}>
              <CopyIcon />
              <span>{TEXT.menuCopy}</span>
            </button>
          </li>
          <li role="none">
            <button
              type="button"
              role="menuitem"
              className={styles.menuItem}
              onClick={() => {
                setViewing(menuPage);
                closeMenu(false);
              }}>
              <FileTextIcon />
              <span>{TEXT.menuView}</span>
            </button>
          </li>
          <li role="separator" className={styles.separator} />
          {launches.map(({tool, href, needsClipboard}) => (
            <li key={tool.id} role="none">
              {/* A real link: works with middle-click/keyboard and isn't
                  subject to popup blockers, unlike window.open. */}
              <a
                role="menuitem"
                className={styles.menuItem}
                href={href}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => {
                  // Too long for the link: the tool gets the page URL, and
                  // the full Markdown is put on the clipboard to paste.
                  if (needsClipboard) void copy(menuPage, tool);
                  closeMenu(false);
                }}>
                <tool.Logo />
                <span>{openInLabel(tool)}</span>
                <ExternalLinkIcon className={styles.externalIcon} />
              </a>
            </li>
          ))}
        </ul>
      )}

      {viewing && (
        <MarkdownDialog
          markdown={viewing.markdown}
          copyStatus={status}
          copyLabel={label}
          onCopy={() => void copy(viewing)}
          onClose={() => {
            setViewing(null);
            toggleRef.current?.focus();
          }}
        />
      )}

      <span className={styles.visuallyHidden} role="status" aria-live="polite">
        {announcement}
      </span>
    </div>
  );
}
